import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { fixture } from './fixtures.mjs';

test('PostgreSQL migration: data preservation, auth, privacy, conflict and idempotency',async()=>{
  const pg=new PGlite();
  const admin='00000000-0000-0000-0000-000000000001';
  const outsider='00000000-0000-0000-0000-000000000002';
  await pg.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key,email text);
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    grant usage on schema auth to anon,authenticated; grant execute on function auth.uid() to anon,authenticated;
    create table public.pickleball_club(id bigint primary key,data jsonb,updated_at timestamptz);
    insert into auth.users values('${admin}','amaquangvp@gmail.com'),('${outsider}','outsider@example.invalid');`);
  const original=fixture();original.transactions=[{id:'tx',type:'income',amount:500,description:'private',category:'fund',date:'2026-09-23'}];
  await pg.query('insert into pickleball_club values(1,$1,now())',[original]);
  await pg.exec(await fs.readFile('supabase/migrations/202609230001_safe_club.sql','utf8'));
  assert.deepEqual((await pg.query('select data from pickleball_club')).rows[0].data,original);
  assert.equal((await pg.query('select count(*) from club_private.pre_migration_backup')).rows[0].count,1);
  await pg.exec(await fs.readFile('supabase/bootstrap-admin.sql','utf8'));
  await pg.exec('set role anon');
  const publicData=(await pg.query('select club_public_read(1) as result')).rows[0].result.data;
  assert.equal(publicData.members[0].phone,undefined);assert.deepEqual(publicData.transactions,[]);
  await assert.rejects(()=>pg.query('select * from pickleball_club'));
  await assert.rejects(()=>pg.query('select club_save(1,0,$1,$2)',[original,'anon-op']));
  await pg.exec(`reset role;set role authenticated;set request.jwt.claim.sub='${outsider}'`);
  await assert.rejects(()=>pg.query('select club_read(1)'));
  await assert.rejects(()=>pg.query('select club_save(1,0,$1,$2)',[original,'outsider-op']));
  await pg.exec(`set request.jwt.claim.sub='${admin}'`);
  assert.equal((await pg.query('select club_my_role(1) as role')).rows[0].role,'admin');
  await assert.rejects(()=>pg.query('update pickleball_club set data=$1 where id=1',[original]));
  const a=structuredClone(original);a.members[0].name='Admin A';
  const saved=(await pg.query('select club_save(1,0,$1,$2) as result',[a,'operation-a'])).rows[0].result;
  assert.equal(saved.revision,1);
  const retry=(await pg.query('select club_save(1,0,$1,$2) as result',[a,'operation-a'])).rows[0].result;
  assert.equal(retry.alreadySaved,true);assert.equal(retry.revision,1);
  const b=structuredClone(original);b.members[1].name='Admin B';
  const conflict=(await pg.query('select club_save(1,0,$1,$2) as result',[b,'operation-b'])).rows[0].result;
  assert.equal(conflict.conflict,true);assert.equal(conflict.current.data.members[0].name,'Admin A');
  await assert.rejects(()=>pg.query('select club_save(1,1,$1,$2)',[b,'operation-a']));
  const bad=structuredClone(a);bad.transactions.push({id:'bad',type:'income',amount:-100});
  await assert.rejects(()=>pg.query('select club_save(1,1,$1,$2)',[bad,'bad-op']));
  const locked=structuredClone(a);locked.events[0].isLocked=true;
  await pg.query('select club_save(1,1,$1,$2)',[locked,'lock-event']);
  const removed=structuredClone(locked);removed.events=[];
  await assert.rejects(()=>pg.query('select club_save(1,2,$1,$2)',[removed,'delete-locked']));
  const forged=structuredClone(locked);forged.matches=[{id:'forged',type:'singles',eventId:'event',teamA:['a'],teamB:['b'],scoreA:11,scoreB:9,played:true,date:'2026-09-23'}];
  await assert.rejects(()=>pg.query('select club_save(1,2,$1,$2)',[forged,'change-locked']));
  await assert.rejects(()=>pg.query('select club_save(2,0,$1,$2)',[original,'cross-club']));
  await pg.exec('reset role');
  assert.deepEqual((await pg.query('select data from club_private.history where revision=0')).rows[0].data,original);
  await pg.close();
});

test('migration rolls back entirely if the intended admin account does not exist',async()=>{
  const pg=new PGlite();
  await pg.exec(`create role anon; create role authenticated; create schema auth;
    create table auth.users(id uuid primary key,email text);
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    create table public.pickleball_club(id bigint primary key,data jsonb,updated_at timestamptz);`);
  const original=fixture();
  await pg.query('insert into public.pickleball_club values(1,$1,now())',[original]);
  const migration=await fs.readFile('supabase/migrations/202609230001_safe_club.sql','utf8');
  await assert.rejects(()=>pg.exec(migration));
  await pg.exec('rollback');
  assert.deepEqual((await pg.query('select data from public.pickleball_club where id=1')).rows[0].data,original);
  assert.equal((await pg.query("select count(*) from information_schema.columns where table_schema='public' and table_name='pickleball_club' and column_name='revision'")).rows[0].count,0);
  assert.equal((await pg.query("select count(*) from pg_namespace where nspname='club_private'")).rows[0].count,0);
  await pg.close();
});

test('manager role can edit club play data without reading or changing finances',async()=>{
  const pg=new PGlite();
  const admin='00000000-0000-0000-0000-000000000001';
  const manager='00000000-0000-0000-0000-000000000003';
  await pg.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    grant usage on schema auth to anon,authenticated; grant execute on function auth.uid() to anon,authenticated;
    create table public.pickleball_club(id bigint primary key,data jsonb,updated_at timestamptz);
    insert into auth.users values('${admin}','amaquangvp@gmail.com',now()),('${manager}','amaquangvp+phoquanly@gmail.com',now());`);
  const original=fixture();original.transactions=[{id:'tx',type:'income',amount:500,description:'private',category:'fund',date:'2026-09-23'}];
  await pg.query('insert into pickleball_club values(1,$1,now())',[original]);
  await pg.exec(await fs.readFile('supabase/migrations/202609230001_safe_club.sql','utf8'));
  await pg.exec(await fs.readFile('supabase/migrations/202609290001_manager_role.sql','utf8'));
  assert.deepEqual((await pg.query('select data from pickleball_club')).rows[0].data,original);
  assert.equal((await pg.query('select count(*) from club_private.pre_migration_backup')).rows[0].count,2);
  await pg.exec(`set role authenticated;set request.jwt.claim.sub='${manager}'`);
  await assert.rejects(()=>pg.query('select club_read(1)'));
  await pg.exec('reset role');
  await pg.exec(await fs.readFile('supabase/grant-manager.sql','utf8'));
  await pg.exec(`set role authenticated;set request.jwt.claim.sub='${manager}'`);
  assert.equal((await pg.query('select club_my_role(1) as role')).rows[0].role,'manager');
  const restricted=(await pg.query('select club_read(1) as result')).rows[0].result;
  assert.deepEqual(restricted.data.transactions,[]);
  assert.equal((await pg.query('select * from pickleball_club')).rows.length,0);
  const edited=structuredClone(restricted.data);edited.members[0].name='Manager edit';
  const saved=(await pg.query('select club_save(1,0,$1,$2) as result',[edited,'manager-edit'])).rows[0].result;
  assert.equal(saved.revision,1);
  const retry=(await pg.query('select club_save(1,0,$1,$2) as result',[edited,'manager-edit'])).rows[0].result;
  assert.equal(retry.alreadySaved,true);
  const conflict=(await pg.query('select club_save(1,0,$1,$2) as result',[edited,'manager-conflict'])).rows[0].result;
  assert.equal(conflict.conflict,true);assert.deepEqual(conflict.current.data.transactions,[]);
  const forged=structuredClone(edited);forged.transactions=[{id:'fake',type:'expense',amount:1}];
  await assert.rejects(()=>pg.query('select club_save(1,1,$1,$2)',[forged,'manager-finance']));
  await pg.exec('reset role');
  const actual=(await pg.query('select data from pickleball_club')).rows[0].data;
  assert.equal(actual.members[0].name,'Manager edit');
  assert.deepEqual(actual.transactions,original.transactions);
  await pg.close();
});
